### ISSUE TITLE
Targets

### ISSUE THREAD

**Issue by valamuri2020** [valamuri2020/NewVision#4]
- [x] Sign In, Register, List, Dashboard Pages - 3/21/21 
- [x] Authentication - 3/21/21
- [x] Get DB working/basic CRUD - 4/4/21
     - [x]  - list page
     - [x]  - dashboard page
     - [x]  - connect auth and crud
- [x] Upload College dataset to firestore DB - 4/4/21
- [x] Search bar - 3/28/21
- [x] figure out how to send user data to backend
- [x] finalize university card design with links
- [x] scrape and clean data for Canadian unis - 4/4/21
- [x] write readme
- [x] finalize UI
- [x] comment code
- [x] develop ML model
- [x] recommendations card
- [x] develop Flask API and connect model to UI
- [x] code cleanup
- [x] data viz and clean on jupyter notebook 
Project Finish - 4/25/21

**Comment by Kshitij-Kumar123** [comment]
done!
